import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { trpc } from '../utils/trpc'

type TechnologyCardProps = {
  name: string
  description: string
  documentation: string
}

const Home: NextPage = () => {
  const [snippetText, setSnippetText] = useState('')

  const snippet = trpc.useMutation(['snippet.saveSnippet'])

  const hello = trpc.useQuery([
    'snippet.hello',
    { text: 'from my tRPC project' },
  ])

  const handleSaveSnipplet = async () => {
    const newSnippet = await snippet.mutateAsync({ text: snippetText })
    console.log('new snip: ', newSnippet)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <p className="text-2xl text-gray-700">Paste bin</p>

        <div className="pt-6 text-2xl text-green-500 flex justify-center items-center w-full">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <textarea
          className="border rounded p-2 w-1/2 h-40"
          value={snippetText}
          name="text1"
          onChange={(e) => setSnippetText(e.target.value)}
        ></textarea>

        <button className="btn-primary my-4 " onClick={handleSaveSnipplet}>
          Save
        </button>
      </main>
    </>
  )
}

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  )
}

export default Home
