import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'

const SnippetPage = () => {
  const router = useRouter()
  const id = router.query.id

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <p className="text-2xl text-gray-700">Paste bin</p>

        <div className="pt-6 text-2xl text-green-500 flex justify-center items-center w-full">
          <div>SnippetPage id :{id}</div>
        </div>
      </main>
    </>
  )
}

export default SnippetPage
